### PR TITLE
Upgrade minimist to 0.2.1

### LINKED ISSUE #7: ship a fix for mkdirp@0.5.1 due minimist
hi,

I've been using `mkdirp` for a while in the `0.x` version. https://www.npmjs.com/package/mkdirp your library has a massive amount of downloads and still many dependencies use it.

Recently was announced a security vulnerability at *minimist*, 

https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764

a dependency which `mkdirp@0.5.1` still use and it is pinned 

https://github.com/isaacs/node-mkdirp/blob/d4eff0f06093aed4f387e88e9fc301cb76beedc7/package.json

I'm asking to ship a fix for `mkdirp@0.5.x` updating minimist. At Verdaccio also we use it, I had some breaking changes but was an easy fix, but we have several transitive dependencies that might not update anytime soon due to the breaking changes.

Screen Shot 2020-03-12 at 7 52 03 AM

### PR DESCRIPTION
**Pull request by mKeRix**
Fixes #7 - vulnerability in dependency:
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

I created a new branch from commit d4eff0f06093aed4f387e88e9fc301cb76beedc7 called v0.x for this fix. Unfortunately I can't create a PR based on a non-existent branch on your repo, so I would appreciate it a lot if you could create a branch off that commit as well, merge this PR there and then release v0.5.2 to npm.

### CODE REVIEW

**Comment by karlhorky** [comment]
**Edit:** Use `mkdirp@0.5.3` - the problem is fixed there.

For anyone looking for a fix for the interim, using Yarn Resolutions you can specify this version number, even though it doesn't match the semver range of `mkdirp`.

Add this to your `package.json` if you're using Yarn and run `yarn` to update your lockfile:

```json
  "resolutions": {
    "**/mkdirp/minimist": "0.2.1"
  }
```

**Comment by canpolatoral** [comment]
When will you merge this pull request?

**Comment by JaymoKang** [comment]
@isaacs

**Review by Seidel-Michael — APPROVED** [review]

**Comment by LinusU** [comment]
This have already been released as `0.5.3` on Npm, please see #7 for more details.

**Comment by mKeRix** [comment]
Thanks for the fix @isaacs!

**Pull request closed without merging**
