### PR TITLE
Rename readme.markdown to readme.md

### PR DESCRIPTION
**Pull request by pkuczynski**
Not a major thing, but `md` seems more popular extension?

### CODE REVIEW

**Comment by pkuczynski** [comment]
Failure of CI is not connected with these changes...

**Comment by isaacs** [comment]
Keeping it `.markdown` in honor of Mr. James "Substack" Halliday

**Comment by pkuczynski** [comment]
Out of interest, what does he has in common with this extension? I am genuinely interested...

**Comment by isaacs** [comment]
He wrote the first version of it. (It's been rewritten by me several times since, of course.)

**Comment by isaacs** [comment]
Oh! Or do you mean the `.markdown` extension? Idk, it's just what he always used.

**Comment by pkuczynski** [comment]
> Oh! Or do you mean the `.markdown` extension? Idk, it's just what he always used.

Yeah, that's what I meant. Not that popular extension for the markdown files these days :) Even you yourself in this repo used `md` for `CHANGELOG`... I thought there might be some extra meaning to it... Thanks for the explanation...

**Pull request closed without merging**
